SELECT * FROM users;
SELECT * FROM addresses;
SELECT * FROM carts;
SELECT * FROM products;
SELECT * FROM images;
SELECT * FROM orders;
SELECT * FROM order_products;
SELECT * FROM cards;
SELECT * FROM favorites;
SELECT * FROM companies;
SELECT * FROM categories;
SELECT * FROM subcategories;
SELECT * FROM brands;

DROP TABLE companies;
DROP TABLE users;
DROP TABLE cards;
DROP TABLE addresses;
DROP TABLE products;
DROP TABLE categories;
DROP TABLE brands;
DROP TABLE subcategories;
DROP TABLE images;
DROP TABLE carts;
DROP TABLE favorites;
DROP TABLE orders;
DROP TABLE order_products;

ALTER TABLE products MODIFY COLUMN cod VARCHAR(45);
ALTER TABLE companies ADD COLUMN zipcode VARCHAR(9) NOT NULL;
ALTER TABLE products CHANGE cod id INT AUTO_INCREMENT;